#external URL for prod proxy
#:crm_path: https://mobileproxy.insphereis.net/

#external URL for model proxy
#:crm_path: https://mobileproxy.model.insphereis.net/

#external URL for dev proxy
:crm_path: http://75.31.122.27/

# :crm_path: http://localhost:5000/
# :crm_path: http://10.174.40.61:5000/